# Generated by Django 4.0.4 on 2022-05-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_question_quiz_remove_result_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quetions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('quetion', models.CharField(max_length=900)),
                ('anser', models.TextField()),
                ('country_time', models.CharField(max_length=300)),
            ],
        ),
    ]
