# Generated by Django 4.0.4 on 2022-05-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_quetions_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='discordID',
            field=models.TextField(null=True),
        ),
    ]
